"""
GitHub API helpers: post PR review comment and open a fixing PR.
"""
from __future__ import annotations

import base64
import hashlib
import os
from typing import Optional

from github import Github, GithubException
from github.PullRequest import PullRequest
from github.Repository import Repository


def _gh() -> Github:
    token = os.environ["GITHUB_TOKEN"]
    return Github(token)


def get_pr(repo_full_name: str, pr_number: int) -> tuple[Repository, PullRequest]:
    g = _gh()
    repo = g.get_repo(repo_full_name)
    pr = repo.get_pull(pr_number)
    return repo, pr


def get_changed_migration_files(repo: Repository, pr: PullRequest, path_pattern: str) -> list[str]:
    """
    Return file paths changed in the PR that look like Flyway versioned migrations.
    path_pattern is used as a simple suffix/glob hint — we filter by Flyway naming convention.
    """
    import fnmatch
    changed = []
    for f in pr.get_files():
        if f.status in ("removed",):
            continue
        if fnmatch.fnmatch(f.filename, path_pattern) or _is_flyway_migration(f.filename):
            changed.append(f.filename)
    return changed


def _is_flyway_migration(path: str) -> bool:
    import re
    filename = path.split("/")[-1]
    return bool(re.match(r"^V\d[\d.]*__.*\.sql$", filename, re.IGNORECASE))


def get_file_content(repo: Repository, pr: PullRequest, file_path: str) -> str:
    """Fetch the file content from the PR head branch."""
    content = repo.get_contents(file_path, ref=pr.head.sha)
    return content.decoded_content.decode("utf-8")


def post_pr_comment(
    repo: Repository,
    pr: PullRequest,
    original_sql: str,
    fixed_sql: str,
    file_path: str,
) -> None:
    """Post a PR comment explaining the issue and showing the fix."""
    body = f"""## Flyway Idempotent Guardian

`{file_path}` contains SQL that is **not idempotent** and may fail on re-run or rollback.

<details>
<summary>Original SQL</summary>

```sql
{original_sql}
```

</details>

### Suggested idempotent replacement

```sql
{fixed_sql}
```

> A fixing PR has been opened targeting this branch. You can merge it directly or apply the changes manually.
"""
    pr.create_issue_comment(body)


def open_fix_pr(
    repo: Repository,
    pr: PullRequest,
    file_path: str,
    fixed_content: str,
) -> Optional[str]:
    """
    Create a branch with the fixed file and open a PR against the original PR's base.
    Returns the URL of the new PR.
    """
    short_sha = pr.head.sha[:7]
    fix_branch = f"fix/idempotent-{pr.number}-{short_sha}"

    # Get the current file blob SHA (needed for updating)
    try:
        current = repo.get_contents(file_path, ref=pr.head.ref)
        file_sha = current.sha
    except GithubException:
        file_sha = None

    # Create the fix branch from PR head
    try:
        repo.create_git_ref(
            ref=f"refs/heads/{fix_branch}",
            sha=pr.head.sha,
        )
    except GithubException as e:
        if "already exists" not in str(e):
            raise

    # Commit the fixed file
    commit_message = f"fix: wrap {file_path} with idempotency guards\n\nAuto-generated by flyway-idempotent-guardian for PR #{pr.number}"
    if file_sha:
        repo.update_file(
            path=file_path,
            message=commit_message,
            content=fixed_content,
            sha=file_sha,
            branch=fix_branch,
        )
    else:
        repo.create_file(
            path=file_path,
            message=commit_message,
            content=fixed_content,
            branch=fix_branch,
        )

    # Open the fixing PR
    fix_pr = repo.create_pull(
        title=f"fix: idempotent SQL for PR #{pr.number} — {file_path}",
        body=(
            f"Auto-generated by **flyway-idempotent-guardian**.\n\n"
            f"Wraps `{file_path}` with idempotency guards so the migration is safe to re-run.\n\n"
            f"Closes #{pr.number} (or merge this first, then merge the original PR).\n\n"
            f"> Generated from commit {pr.head.sha[:7]} on branch `{pr.head.ref}`."
        ),
        head=fix_branch,
        base=pr.base.ref,
    )
    return fix_pr.html_url
