"""
Generates idempotent SQL by rendering Jinja2 templates with extracted DDL context.
"""
from __future__ import annotations

import re
import os
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, TemplateNotFound

from sql_detector import DetectionResult, DdlType

_TEMPLATES_DIR = Path(__file__).parent.parent / "templates"

_GUARDIAN_URL = "https://github.com/postman-eng/flyway-idempotent-guardian"

# (op_name, description, warning|None)
_DDL_META: dict[DdlType, tuple[str, str, str | None]] = {
    DdlType.CREATE_TABLE: (
        "CREATE TABLE",
        "Wraps CREATE TABLE with IF NOT EXISTS — skips silently if the table already exists.",
        None,
    ),
    DdlType.ADD_COLUMN: (
        "ADD COLUMN",
        "Wraps ADD COLUMN with an existence check — skips silently if the column is already present.",
        None,
    ),
    DdlType.ALTER_COLUMN_TYPE: (
        "ALTER COLUMN TYPE",
        "Wraps ALTER COLUMN TYPE with an existence check — skips if the column is missing.",
        None,
    ),
    DdlType.CREATE_INDEX: (
        "CREATE INDEX",
        "Wraps CREATE INDEX with IF NOT EXISTS — skips silently if the index already exists.",
        None,
    ),
    DdlType.CREATE_UNIQUE_INDEX: (
        "CREATE UNIQUE INDEX",
        "Wraps CREATE UNIQUE INDEX with IF NOT EXISTS — skips silently if the index already exists.",
        None,
    ),
    DdlType.ADD_FK: (
        "ADD FOREIGN KEY",
        "Wraps ADD FOREIGN KEY with a constraint existence check — skips if already present.",
        None,
    ),
    DdlType.ADD_UNIQUE: (
        "ADD UNIQUE CONSTRAINT",
        "Wraps ADD UNIQUE with a constraint existence check — skips if already present.",
        None,
    ),
    DdlType.ADD_CHECK: (
        "ADD CHECK CONSTRAINT",
        "Wraps ADD CHECK with a constraint existence check — skips if already present.",
        None,
    ),
    DdlType.DROP_COLUMN: (
        "DROP COLUMN",
        "Wraps DROP COLUMN with an existence check — skips if the column is already gone.",
        "DESTRUCTIVE: permanently removes the column and its data. Cannot be undone without a restore.",
    ),
    DdlType.DROP_TABLE: (
        "DROP TABLE",
        "Wraps DROP TABLE with IF EXISTS — skips silently if the table is already gone.",
        "DESTRUCTIVE: permanently deletes the table and all data. "
        "Dependent-object handling varies by dialect and rendered SQL; verify this is intentional before merging.",
    ),
    DdlType.CREATE_TYPE: (
        "CREATE TYPE",
        "Wraps CREATE TYPE with an existence check — skips silently if the type is already defined.",
        None,
    ),
    DdlType.ADD_NOT_NULL: (
        "SET NOT NULL",
        "Wraps SET NOT NULL with a nullability check. Existing NULLs may be rewritten to a non-NULL value before the constraint is applied, depending on dialect.",
        "DATA CHANGE: any NULL values in this column may be rewritten before NOT NULL is enforced. "
        "Verify the generated SQL and resulting replacement value for your dialect before merging.",
    ),
    DdlType.RENAME_COLUMN: (
        "RENAME COLUMN",
        "Wraps RENAME COLUMN with checks on both old and new names — skips if already renamed or source is missing.",
        None,
    ),
    DdlType.DROP_CONSTRAINT: (
        "DROP CONSTRAINT",
        "Wraps DROP CONSTRAINT with an existence check — skips if the constraint is already gone.",
        None,
    ),
    DdlType.CREATE_VIEW: (
        "CREATE VIEW",
        "Rewrites CREATE VIEW as CREATE OR REPLACE VIEW — safe to re-run without dropping first.",
        None,
    ),
    DdlType.CREATE_FUNCTION: (
        "CREATE FUNCTION",
        "Rewrites CREATE FUNCTION as CREATE OR REPLACE FUNCTION — safe to re-run without dropping first.",
        None,
    ),
}


def _env(dialect: str) -> Environment:
    loader = FileSystemLoader([
        str(_TEMPLATES_DIR / dialect),
        str(_TEMPLATES_DIR / "shared"),
    ])
    return Environment(loader=loader, trim_blocks=True, lstrip_blocks=True)


def _build_header(ddl_type: DdlType, pr_author: str, pr_url: str) -> str:
    """Build the header comment block for non-template code paths."""
    op_name, description, warning = _DDL_META.get(ddl_type, ("UNKNOWN", "", None))
    lines = [
        "-- =================================================================",
        "-- Generated by flyway-idempotent-guardian",
        f"-- {_GUARDIAN_URL}",
        "-- -----------------------------------------------------------------",
        f"-- Operation   : {op_name}",
        f"-- Description : {description}",
    ]
    if warning:
        lines.append(f"-- !! WARNING  : {warning}")
    author_line = f"-- PR Author   : @{pr_author}"
    if pr_url:
        author_line += f" ({pr_url})"
    lines.append(author_line)
    lines.append("-- =================================================================")
    return "\n".join(lines) + "\n"


_DDL_TEMPLATE_MAP: dict[DdlType, str] = {
    DdlType.CREATE_TABLE: "create_table.sql.j2",
    DdlType.ADD_COLUMN: "add_column.sql.j2",
    DdlType.ALTER_COLUMN_TYPE: "alter_column_type.sql.j2",
    DdlType.CREATE_INDEX: "create_index.sql.j2",
    DdlType.CREATE_UNIQUE_INDEX: "create_index.sql.j2",
    DdlType.ADD_FK: "add_constraint.sql.j2",
    DdlType.ADD_UNIQUE: "add_constraint.sql.j2",
    DdlType.ADD_CHECK: "add_constraint.sql.j2",
    DdlType.DROP_COLUMN: "drop_column.sql.j2",
    DdlType.DROP_TABLE: "drop_table.sql.j2",
    DdlType.CREATE_TYPE: "create_type.sql.j2",
    DdlType.ADD_NOT_NULL: "add_not_null.sql.j2",
    DdlType.RENAME_COLUMN: "rename_column.sql.j2",
    DdlType.DROP_CONSTRAINT: "drop_constraint.sql.j2",
    DdlType.CREATE_VIEW: None,      # CREATE OR REPLACE VIEW is already idempotent
    DdlType.CREATE_FUNCTION: None,  # CREATE OR REPLACE FUNCTION is already idempotent
}

_CONSTRAINT_TYPE_MAP = {
    DdlType.ADD_FK: "FOREIGN KEY",
    DdlType.ADD_UNIQUE: "UNIQUE",
    DdlType.ADD_CHECK: "CHECK",
}


def wrap(result: DetectionResult, pr_author: str = "unknown", pr_url: str = "") -> str:
    """
    Return idempotent SQL for the given DetectionResult.
    Returns the original SQL unchanged if it is already idempotent or unknown.
    Returns a comment placeholder if no template exists for the type.
    """
    if result.already_idempotent:
        return result.raw

    if result.ddl_type == DdlType.UNKNOWN:
        return (
            f"-- WARNING: flyway-idempotent-guardian could not classify this statement.\n"
            f"-- Manual idempotency review required.\n{result.raw}"
        )

    template_name = _DDL_TEMPLATE_MAP.get(result.ddl_type)

    # Views/functions: rewrite to use CREATE OR REPLACE (no template)
    if result.ddl_type == DdlType.CREATE_VIEW:
        rewritten = re.sub(
            r"CREATE\s+VIEW", "CREATE OR REPLACE VIEW", result.raw, count=1, flags=re.IGNORECASE
        )
        return _build_header(result.ddl_type, pr_author, pr_url) + "\n" + rewritten
    if result.ddl_type == DdlType.CREATE_FUNCTION:
        rewritten = re.sub(
            r"CREATE\s+FUNCTION", "CREATE OR REPLACE FUNCTION", result.raw, count=1, flags=re.IGNORECASE
        )
        return _build_header(result.ddl_type, pr_author, pr_url) + "\n" + rewritten

    if template_name is None:
        return (
            f"-- WARNING: No idempotency template for {result.ddl_type}.\n"
            f"-- Manual review required.\n{result.raw}"
        )

    try:
        env = _env(result.dialect)
        template = env.get_template(template_name)
    except TemplateNotFound:
        return (
            f"-- WARNING: Template '{template_name}' not found for dialect '{result.dialect}'.\n"
            f"-- Manual review required.\n{result.raw}"
        )

    op_name, description, warning = _DDL_META.get(result.ddl_type, ("UNKNOWN", "", None))
    ctx = {
        "schema": result.schema or "public",
        "table": result.table or "unknown_table",
        "column": result.column,
        "new_column": result.new_column,
        "index": result.index,
        "constraint": result.constraint,
        "type_name": result.type_name,
        "raw": result.raw,
        "unique": result.ddl_type == DdlType.CREATE_UNIQUE_INDEX,
        "constraint_type": _CONSTRAINT_TYPE_MAP.get(result.ddl_type, ""),
        # Header variables
        "guardian_url": _GUARDIAN_URL,
        "op_name": op_name,
        "description": description,
        "warning": warning,
        "pr_author": pr_author,
        "pr_url": pr_url,
    }

    return template.render(**ctx).strip()
